# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: stochax-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.12" ]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.os }} ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies and source code
      run: |
        python -m pip install --upgrade pip
        pip install .[build,docs]
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        mkdir -p tests/test-reports
        # flake8 stochax --format junit-xml >tests/test-reports/TEST-test_flake8-"$(date +"%Y%m%d%H%M%S")".xml
        ruff check stochax
    - name: Test library
      run: |
        cd tests
        bash battery.sh
